# Generated by Django 2.2.3 on 2019-07-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.IntegerField()),
                ('cpf', models.IntegerField()),
                ('vinculo', models.CharField(choices=[('Servidor', 'Servidor'), ('Terceirizado', 'Terceirizado')], max_length=12)),
                ('disciplina', models.CharField(choices=[('Telecomunicações', 'Telecomunicações'), ('Arquitetura', 'Arquitetura'), ('Elétrica', 'Elétrica'), ('Estruturas', 'Estruturas')], max_length=20)),
                ('obs', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('obs', models.TextField(null=True)),
            ],
        ),
    ]
