# Generated by Django 2.2.3 on 2019-07-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='obs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
