# Generated by Django 2.2.3 on 2019-07-17 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('Obra', 'Obra'), ('Continuado', 'Continuado')], max_length=10)),
                ('empresa', models.CharField(max_length=100)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_contratado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=False)),
                ('percent_acres', models.FloatField(default=0)),
                ('percent_sup', models.FloatField(default=0)),
                ('percent_med', models.FloatField(default=0)),
                ('percent_apost', models.FloatField(default=0)),
                ('obs', models.TextField(null=True)),
                ('fiscal', models.ManyToManyField(to='cadastro.Fiscal')),
                ('processo_pai', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos.Processo')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.Unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('evento', models.CharField(choices=[('Medição', 'Medição'), ('Apostilamento', 'Apostilamento'), ('Aditivo de Acréscimo', 'Aditivo de Acréscimo'), ('Aditivo de Supressão', 'Aditivo de Supressão')], max_length=30)),
                ('data_1', models.DateField()),
                ('data_2', models.DateField(null=True)),
                ('valor_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percent_event', models.FloatField(default=0)),
                ('obs', models.TextField(null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Processo')),
                ('origem', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos.Medicao')),
            ],
        ),
    ]
